import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // Sidebar
        home: 'Home',
        explore: 'Explore',
        world: 'Vibe World',
        community: 'Community',
        forum: 'Forum',
        profile: 'Profile',
        shop: 'Shop',
        premium: 'Premium',
        vinylGoal: 'Vinyl Goal',
        library: 'Library',
        create: 'Create',
        feedTitle: 'Top 10 Vibes',
        forYou: 'For You',
        following: 'Following',
        giveGold: 'Give Gold',
        play: 'Play',
        voted: 'Voted',
        searchPlaceholder: 'Search tracks, artists, vibes... (Cmd+K)',
        userProfile: 'User Profile',

        // Login
        welcomeBack: 'Welcome Back',
        studioAwaits: 'Your studio awaits.',
        emailPlaceholder: 'Email',
        passwordPlaceholder: 'Password',
        signIn: 'Sign In',
        signingIn: 'Signing In...',
        continueWithGoogle: 'Continue with Google',
        continueAsGuest: 'Continue as Guest',
        dontHaveAccount: "Don't have an account?",
        signUp: 'Sign Up',
        or: 'OR',

        // Road to Vinyl
        rtvTitle: 'Road to Vinyl',
        rtvSubtitle: 'The ultimate journey for every Vibe Music artist. Reach 50,000 Vibe Points to unlock a',
        rtvFreeVinyl: 'FREE custom vinyl pressing of your best work.',
        totalProgress: 'Total Progress',
        pointsAway: 'points away from',
        vinylReached: 'Vinyl Legend Reached! Contact support to claim your reward.',
        questJourney: 'Quest Journey',
        reward: 'Reward',

        // Milestones
        bronzeLabel: 'Bronze Producer',
        silverLabel: 'Silver Artist',
        goldLabel: 'Gold Star',
        vinylLabel: 'Vinyl Legend',
        bronzeReward: 'Bronze Profile Badge',
        silverReward: 'Private Collab Access',
        goldReward: 'Featured Artist Spot',
        vinylReward: '100 Free Custom Vinyls',
        rookieLabel: 'Rookie',

        // Earn Methods
        earnMethod1Title: 'Community Feedback',
        earnMethod1Desc: 'Rate and review 5 new tracks',
        earnMethod2Title: 'Daily Session',
        earnMethod2Desc: 'Log in and stay active for 30 mins',
        earnMethod3Title: 'Collaborator',
        earnMethod3Desc: 'Complete a collab in the World Canvas',
        earnMethod4Title: 'Viral Vibe',
        earnMethod4Desc: 'Get 100+ plays on a single day',
        earnMethod5Title: 'Active Listener',
        earnMethod5Desc: 'Listen for 1 hour',
        earnMethod6Title: 'Super Fan',
        earnMethod6Desc: 'Listen for 5 hours',

        // Vinyl Showcase
        ultimatePrize: 'The Ultimate Prize',
        prizeDesc: 'Once you reach 50,000 points, we cover everything. Professional mastering, custom artwork design, and shipping of 100 high-quality 12" vinyls to your studio.',
        physicalRelease: 'Physical Release',
        included: 'Included',
        globalShipping: 'Global Shipping',
        worldwide: 'Worldwide',
        totalCost: 'Total Cost',
        freeCost: '0 Vibe Points',
        shareProgress: 'Share Progress',

        // Create Page
        createPageTitle: 'Create & Generate',
        createPageSubtitle: 'Access powerful tools to spark your creativity.',
        uploadTrackTitle: 'Upload New Track',
        uploadTrackDesc: 'Upload your finished audio files (MP3, WAV) to publish to your profile and the feed.',
        uploadNow: 'Upload Now',

        // Tools
        toolLyricTitle: 'Lyric Assistant',
        toolLyricDesc: 'Generate rhymes and flow suggestions instantly.',
        toolBeatTitle: 'Beat Matcher',
        toolBeatDesc: 'Find the perfect beat for your vocal track.',
        toolChordTitle: 'Chord Wizard',
        toolChordDesc: 'Suggests progressions to match your melody.',
        toolVoiceTitle: 'Voice FX Studio',
        toolVoiceDesc: 'Apply professional effects to your recordings.',
        toolRapTitle: 'Rap Battle Arena',
        toolRapDesc: 'Challenge others and test your freestyle skills.',
        toolRtvTitle: 'Road to Vinyl',
        toolRtvDesc: 'Track your progress and achievements.',

        // Premium
        premTitle: 'Upgrade Your Career',
        premSubtitle: 'Tools for serious artists. Cancel anytime.',
        monthly: 'Monthly',
        yearly: 'Yearly (-20%)',
        free: 'Free',
        currentPlan: 'Current Plan',
        upgrade: 'Upgrade',
        startCreating: 'Start Creating',
        goPro: 'Go Pro',
        contactSales: 'Contact Sales',
        mostPopular: 'MOST POPULAR',
        // Premium Tiers
        tierListener: 'Listener',
        tierListenerPro: 'Listener Pro',
        tierBeginner: 'Beginner / Supporter',
        tierPro: 'Pro Artist',
        tierLabel: 'Label',
        // Premium Features
        featAdSupported: 'Ad-supported listening',
        featStdAudio: 'Standard Audio Quality',
        featFollow5: 'Follow 5 Artists',
        featAdFree: 'Ad-Free Listening',
        featPromote1: 'Promote 1 Own Album',
        featRankings: 'Join Rankings',
        featHqAudio: 'High Quality Audio',
        featUpload5: 'Upload 5 Tracks',
        featBasicStats: 'Basic Analytics',
        featSupportPlat: 'Support the Platform',
        featBadge: 'Supporter Badge',
        featUnlimUploads: 'Unlimited Uploads',
        featHiRes: 'Hi-Res Audio (FLAC)',
        featAdvStats: 'Advanced Analytics',
        featVerifBadge: 'Verification Badge',
        featRoyalties: 'Keep 100% Royalties',
        featManage5: 'Manage 5 Artists',
        featPriSupport: 'Priority Support',
        featTrend: 'Trend Forecasting',
        featLegal: 'Legal Aid Access',
        featApi: 'API Access',

        // Profile
        badgeProducer: 'PRODUCER',
        badgeVerified: 'VERIFIED',
        statVibePoints: 'Vibe Points',
        statTracks: 'Tracks',
        statFans: 'Fans',
        vinylGoalTitle: 'Vinyl Goal 💿',
        vinylPoints: 'Points',
        vinylCongrats: "Congratulations! You've earned a Vinyl Release! 🚀",
        vinylMorePoints: 'more points to get your music pressed on Vinyl.',
        refLink: 'Your Referral Link',
        refDesc: 'Bring 10 friends to earn 2,000 points!',
        copy: 'Copy',
        waysToEarn: 'Ways to Earn',
        earnRate: 'Rate Tracks',
        earnRateDesc: '+5 per rate',
        earnUpload: 'Upload Music',
        earnUploadDesc: '+50 per track',
        earnRefer: 'Refer Friend',
        earnReferDesc: '+200 per sign-up',
        myReleases: 'My Releases',

        // Explore
        expTitle: 'Vibe Expansion Hub',
        expSubtitle: 'Discover the sonic universe. Trending tracks, rising stars, and collaborative masterpieces.',
        trendingArtists: 'Trending Artists',
        globalWaves: 'Global Waves',
        creativeArena: 'Creative Arena',
        followers: 'Followers',
        plays: 'plays',

        // Shop
        supportWork: 'Support Our Work',
        supportDesc: 'One-time contributions to fuel the platform and your career. No subscriptions.',
        tierSupporter: 'Supporter',
        tierSuper: 'Super Supporter',
        tierMega: 'Mega Supporter',
        tierGargantuan: 'Gargantuan Supporter',
        tierAbsolute: 'ABSOLUTE SUPPORTER',
        featLicense: 'Free License for MASTER! Suit!',
        featImport1: 'Import 1 Full Album (One Time)',
        featImport2: 'Import 2 Full Albums',
        featImport3: 'Import 3 Full Albums',
        featAllPrev: 'All Previous Benefits',
        featTopCharts: 'Top of Charts Placement (1 Week)',
        featHighlight: 'Highlighted Profile',
        feat10Albums: '10 Albums on Main Page',
        featVidTools: 'Music Video Gen Tools Access',
        featVidChannel: 'Own Music Video Channel',
        featTshirts: '5x Custom T-Shirts (By Us)',
        featPosters: '10x Custom Posters (By Us)',
        legend: 'LEGEND',
        godlike: 'GODLIKE',
        support: 'Support',
        oneTime: 'one-time',

        // Admin
        adminTitle: 'Command Center',
        sysStatus: 'System Status',
        online: 'ONLINE',
        loggedInAs: 'Logged in as',
        tabOverview: 'Overview',
        tabUsers: 'User Management',
        statUsers: 'Total Users',
        statRev: 'Monthly Revenue',
        statFlags: 'Active Flags',
        statLoad: 'Server Load',
        netTraffic: 'Network Traffic',
        recentFlags: 'Recent Flags',
        viewAll: 'View All',
        user: 'User',
        reason: 'Reason',
        time: 'Time',
        status: 'Status',
        action: 'Action',
        quickActions: 'Quick Actions',
        bcastAlert: 'Broadcast Alert',
        verifyReq: 'Verify Requests',
        maintMode: 'Maintenance Mode',
        secAlert: 'Security Alert',
        secMsg: 'Unusual login attempts detected from IP range 192.168.x.x provided by VPN services.',
        investigate: 'Investigate',
        regUsers: 'Registered Users Management',
        username: 'Username',
        email: 'Email',
        currentRole: 'Current Role',
        actions: 'Actions',
        promote: 'Promote to Admin',
        demote: 'Demote',
        noUsers: 'No users found in Mock DB. Try registering some users!',
        cannotDemote: 'Cannot demote Super Admin'
    },
    pl: {
        // Sidebar
        home: 'Strona Główna',
        explore: 'Eksploruj',
        world: 'Świat Vibe',
        community: 'Społeczność',
        forum: 'Forum',
        profile: 'Profil',
        shop: 'Sklep',
        premium: 'Premium',
        vinylGoal: 'Cel Winylowy',
        library: 'Biblioteka',
        create: 'Utwórz',
        feedTitle: 'Top 10 Utworów',
        forYou: 'Dla Ciebie',
        following: 'Obserwowane',
        giveGold: 'Daj Złoto',
        play: 'Odtwórz',
        voted: 'Zagłosowano',
        searchPlaceholder: 'Szukaj utworów, artystów, wibracji... (Cmd+K)',
        userProfile: 'Profil Użytkownika',

        // Login
        welcomeBack: 'Witaj Ponownie',
        studioAwaits: 'Twoje studio czeka.',
        emailPlaceholder: 'Email',
        passwordPlaceholder: 'Hasło',
        signIn: 'Zaloguj się',
        signingIn: 'Logowanie...',
        continueWithGoogle: 'Kontynuuj z Google',
        continueAsGuest: 'Kontynuuj jako Gość',
        dontHaveAccount: 'Nie masz konta?',
        signUp: 'Zarejestruj się',
        or: 'LUB',

        // Road to Vinyl
        rtvTitle: 'Droga do Winyla',
        rtvSubtitle: 'Ostateczna podróż dla każdego artysty Vibe Music. Zdobądź 50 000 Punktów Vibe, aby odblokować',
        rtvFreeVinyl: 'DARMOWE tłoczenie winyli z Twoją najlepszą twórczością.',
        totalProgress: 'Całkowity Postęp',
        pointsAway: 'punktów do',
        vinylReached: 'Legenda Winylowa! Skontaktuj się z pomocą techniczną, aby odebrać nagrodę.',
        questJourney: 'Podróż Przygodowa',
        reward: 'Nagroda',

        // Milestones
        bronzeLabel: 'Brązowy Producent',
        silverLabel: 'Srebrny Artysta',
        goldLabel: 'Złota Gwiazda',
        vinylLabel: 'Legenda Winylowa',
        bronzeReward: 'Brązowa Odznaka Profilu',
        silverReward: 'Dostęp do Prywatnych Kolaboracji',
        goldReward: 'Wyróżnienie Artysty',
        vinylReward: '100 Darmowych Winyli',
        rookieLabel: 'Żółtodziób',

        // Earn Methods
        earnMethod1Title: 'Opinia Społeczności',
        earnMethod1Desc: 'Oceń i zrecenzuj 5 nowych utworów',
        earnMethod2Title: 'Codzienna Sesja',
        earnMethod2Desc: 'Zaloguj się i bądź aktywny przez 30 min',
        earnMethod3Title: 'Współpracownik',
        earnMethod3Desc: 'Ukończ kolaborację w World Canvas',
        earnMethod4Title: 'Wirusowy Vibe',
        earnMethod4Desc: 'Zdobądź 100+ odtworzeń w jeden dzień',
        earnMethod5Title: 'Aktywny Słuchacz',
        earnMethod5Desc: 'Słuchaj przez 1 godzinę',
        earnMethod6Title: 'Super Fan',
        earnMethod6Desc: 'Słuchaj przez 5 godzin',

        // Vinyl Showcase
        ultimatePrize: 'Nagroda Główna',
        prizeDesc: 'Gdy zdobędziesz 50 000 punktów, pokrywamy wszystko. Profesjonalny mastering, projekt okładki i wysyłka 100 wysokiej jakości 12-calowych winyli do Twojego studia.',
        physicalRelease: 'Wydanie Fizyczne',
        included: 'W cenie',
        globalShipping: 'Wysyłka Globalna',
        worldwide: 'Cały Świat',
        totalCost: 'Całkowity Koszt',
        freeCost: '0 Punktów Vibe',
        shareProgress: 'Udostępnij Postęp',

        // Create Page
        createPageTitle: 'Twórz i Generuj',
        createPageSubtitle: 'Uzyskaj dostęp do potężnych narzędzi, aby pobudzić swoją kreatywność.',
        uploadTrackTitle: 'Prześlij Nowy Utwór',
        uploadTrackDesc: 'Prześlij gotowe pliki audio (MP3, WAV), aby opublikować je na swoim profilu i w kanale.',
        uploadNow: 'Prześlij Teraz',

        // Tools
        toolLyricTitle: 'Asystent Tekstów',
        toolLyricDesc: 'Generuj rymy i sugestie flow natychmiastowo.',
        toolBeatTitle: 'Dopasowywanie Bitów',
        toolBeatDesc: 'Znajdź idealny bit do swojego wokalu.',
        toolChordTitle: 'Czarodziej Akordów',
        toolChordDesc: 'Sugeruje progresje pasujące do Twojej melodii.',
        toolVoiceTitle: 'Studio Voice FX',
        toolVoiceDesc: 'Zastosuj profesjonalne efekty do swoich nagrań.',
        toolRapTitle: 'Arena Bitw Rapowych',
        toolRapDesc: 'Rzuć wyzwanie innym i przetestuj swoje umiejętności freestyle.',
        toolRtvTitle: 'Droga do Winyla',
        toolRtvDesc: 'Śledź swoje postępy i osiągnięcia.',

        // Premium
        premTitle: 'Rozwiń Swoją Karierę',
        premSubtitle: 'Narzędzia dla poważnych artystów. Anuluj w każdej chwili.',
        monthly: 'Miesięcznie',
        yearly: 'Rocznie (-20%)',
        free: 'Darmowy',
        currentPlan: 'Obecny Plan',
        upgrade: 'Ulepsz',
        startCreating: 'Zacznij Tworzyć',
        goPro: 'Wybierz Pro',
        contactSales: 'Kontakt',
        mostPopular: 'NAJPOPULARNIEJSZY',
        // Premium Tiers
        tierListener: 'Słuchacz',
        tierListenerPro: 'Słuchacz Pro',
        tierBeginner: 'Początkujący / Wspierający',
        tierPro: 'Artysta Pro',
        tierLabel: 'Wytwórnia',
        // Premium Features
        featAdSupported: 'Słuchanie z reklamami',
        featStdAudio: 'Standardowa jakość dźwięku',
        featFollow5: 'Obserwuj 5 artystów',
        featAdFree: 'Słuchanie bez reklam',
        featPromote1: 'Promuj 1 własny album',
        featRankings: 'Dołącz do rankingów',
        featHqAudio: 'Wysoka jakość dźwięku',
        featUpload5: 'Prześlij 5 utworów',
        featBasicStats: 'Podstawowe statystyki',
        featSupportPlat: 'Wspieraj platformę',
        featBadge: 'Odznaka Wspierającego',
        featUnlimUploads: 'Nielimitowane przesyłanie',
        featHiRes: 'Dźwięk Hi-Res (FLAC)',
        featAdvStats: 'Zaawansowane statystyki',
        featVerifBadge: 'Odznaka weryfikacji',
        featRoyalties: 'Zachowaj 100% tantiem',
        featManage5: 'Zarządzaj 5 artystami',
        featPriSupport: 'Wsparcie priorytetowe',
        featTrend: 'Prognozowanie trendów',
        featLegal: 'Dostęp do pomocy prawnej',
        featApi: 'Dostęp do API',

        // Admin
        adminTitle: 'Centrum Dowodzenia',

        // Profile
        badgeProducer: 'PRODUCENT',
        badgeVerified: 'ZWERYFIKOWANY',
        statVibePoints: 'Punkty Vibe',
        statTracks: 'Utwory',
        statFans: 'Fani',
        vinylGoalTitle: 'Cel Winylowy 💿',
        vinylPoints: 'Punktów',
        vinylCongrats: "Gratulacje! Zdobyłeś Wydanie Winylowe! 🚀",
        vinylMorePoints: 'punktów więcej, aby wytłoczyć swoją muzykę na winylu.',
        refLink: 'Twój Link Polecający',
        refDesc: 'Zaproś 10 znajomych, aby zdobyć 2000 punktów!',
        copy: 'Kopiuj',
        waysToEarn: 'Sposoby na Zarabianie',
        earnRate: 'Oceń Utwory',
        earnRateDesc: '+5 za ocenę',
        earnUpload: 'Prześlij Muzykę',
        earnUploadDesc: '+50 za utwór',
        earnRefer: 'Poleć Znajomego',
        earnReferDesc: '+200 za rejestrację',
        myReleases: 'Moje Wydania',

        // Explore
        expTitle: 'Centrum Ekspansji Vibe',
        expSubtitle: 'Odkryj dźwiękowe uniwersum. Trendy, wschodzące gwiazdy i arcydzieła współpracy.',
        trendingArtists: 'Artyści na Topie',
        globalWaves: 'Globalne Fale',
        creativeArena: 'Kreatywna Arena',
        followers: 'Obserwujących',
        plays: 'odtworzeń',

        // Shop
        supportWork: 'Wspieraj Naszą Pracę',
        supportDesc: 'Jednorazowe wpłaty, aby napędzić platformę i Twoją karierę. Bez subskrypcji.',
        tierSupporter: 'Wspierający',
        tierSuper: 'Super Wspierający',
        tierMega: 'Mega Wspierający',
        tierGargantuan: 'Ogromny Wspierający',
        tierAbsolute: 'ABSOLUTNY WSPIERAJĄCY',
        featLicense: 'Darmowa Licencja na MASTER! Suit!',
        featImport1: 'Import 1 Pełnego Albumu (Jednorazowo)',
        featImport2: 'Import 2 Pełnych Albumów',
        featImport3: 'Import 3 Pełnych Albumów',
        featAllPrev: 'Wszystkie Poprzednie Korzyści',
        featTopCharts: 'Miejsce na Szczycie List (1 Tydzień)',
        featHighlight: 'Wyróżniony Profil',
        feat10Albums: '10 Albumów na Stronie Głównej',
        featVidTools: 'Dostęp do Narzędzi Generowania Teledysków',
        featVidChannel: 'Własny Kanał z Teledyskami',
        featTshirts: '5x Własne Koszulki (Od Nas)',
        featPosters: '10x Własne Plakaty (Od Nas)',
        legend: 'LEGENDA',
        godlike: 'BOSKI',
        support: 'Wspieraj',
        oneTime: 'jednorazowo',
        sysStatus: 'Status Systemu',
        online: 'ONLINE',
        loggedInAs: 'Zalogowany jako',
        tabOverview: 'Przegląd',
        tabUsers: 'Zarządzanie Użytkownikami',
        statUsers: 'Użytkownicy',
        statRev: 'Mies. Przychód',
        statFlags: 'Aktywne Zgłoszenia',
        statLoad: 'Obciążenie Serwera',
        netTraffic: 'Ruch Sieciowy',
        recentFlags: 'Ostatnie Zgłoszenia',
        viewAll: 'Zobacz Wszystkie',
        user: 'Użytkownik',
        reason: 'Powód',
        time: 'Czas',
        status: 'Status',
        action: 'Akcja',
        quickActions: 'Szybkie Akcje',
        bcastAlert: 'Nadaj Alert',
        verifyReq: 'Weryfikuj Prośby',
        maintMode: 'Tryb Konserwacji',
        secAlert: 'Alert Bezpieczeństwa',
        secMsg: 'Wykryto nietypowe próby logowania z zakresu IP 192.168.x.x (VPN).',
        investigate: 'Zbadaj',
        regUsers: 'Zarządzanie Zarejestrowanymi Użytkownikami',
        username: 'Nazwa Użytkownika',
        email: 'Email',
        currentRole: 'Obecna Rola',
        actions: 'Akcje',
        promote: 'Awansuj na Admina',
        demote: 'Degraduj',
        noUsers: 'Brak użytkowników w bazie Mock. Spróbuj kogoś zarejestrować!',
        cannotDemote: 'Nie można zdegradować Super Admina'
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('vibe-language') || 'en';
    });

    useEffect(() => {
        localStorage.setItem('vibe-language', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'pl' : 'en');
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
